### ISSUE TITLE
Instructor Feedback - Problem statement, planning

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [EntJava/jey-blog#3]
@erbecerra @udarc  (for some reason I'm not able to add Yia in the notification, so please share with him).

From our web-ex chat on Tuesday,  you have a solid project idea. I think it will be a useful project and hopefully a lot of fun to build! From a review of the details documented in Jeanne's branch in GitHub I think this sized just right.

- [x] Document what formats your GET responses will support: (xml, json, html, plain?)
- [x] Document what attributes your resources will have (meaning what instance variables are on blogpost)?
- [x] Remember to include the userguide/documentation in your project plan. You might take a look at Swagger as a way to do that documentation. A good place to keep this documentation is probably index.jsp of your service application site. 

Go team!

**Comment by udarc** [comment]
Incorporated items in feedback
